#!/usr/bin/env python3
"""Import the Phase 7 German salary seed into role_salaries.

One-time database population script. Kept for auditability and controlled
reruns while rebuilding the seeded Career Compass database; not app runtime
code. Prefer --dry-run before any write-mode rerun.

Phase 8 writes salary rows into Supabase. It only targets the existing
role_salaries table and maps the reviewed seed CSV into the compact database
schema.
"""

from __future__ import annotations

import argparse
import collections
import csv
import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence


DEFAULT_SEED = Path("data/german_salary_seed.autogenerated.csv")
DEFAULT_SANITY_REVIEW = Path("data/german_salary_seed_sanity_review.csv")
DEFAULT_BATCH_SIZE = 100

ROLE_SALARIES_COLUMNS = [
    "role_id",
    "salary_band",
    "salary_score",
    "salary_median_monthly_gross_eur",
    "region",
    "entgeltatlas_match_title",
    "needs_review",
    "kldb_code",
]


@dataclass(frozen=True)
class ImportStats:
    csv_rows_read: int
    payload_rows: int
    rows_upserted: int
    rows_after_import: int
    region_counts: collections.Counter[str]
    needs_review_counts: collections.Counter[str]
    sanity_review_path: Path | None
    dry_run: bool


class SupabaseError(RuntimeError):
    """Raised when Supabase returns an error response."""


def role_salary_payload_from_seed_row(
    row: Mapping[str, str],
    region_override: str = "",
    sanity_needs_review_by_role_id: Mapping[str, bool] | None = None,
) -> dict[str, Any]:
    role_id = parse_required_int(row.get("role_id"), "role_id")
    region = collapse_spaces(region_override or row.get("region") or "DE")
    needs_review = parse_optional_bool(row.get("needs_review"))
    if sanity_needs_review_by_role_id is not None:
        override = sanity_needs_review_by_role_id.get(str(role_id))
        if override is not None:
            needs_review = override
    return {
        "role_id": role_id,
        "salary_band": optional_text(row.get("salary_band")),
        "salary_score": parse_optional_float(row.get("salary_score")),
        "salary_median_monthly_gross_eur": parse_optional_float(
            row.get("salary_median_monthly_gross_eur")
        ),
        "region": region,
        "entgeltatlas_match_title": optional_text(row.get("entgeltatlas_match_title")),
        "needs_review": needs_review,
        "kldb_code": optional_text(row.get("kldb_code")),
    }


def load_seed_payloads(
    path: Path,
    region_override: str = "",
    sanity_review_path: Path | None = None,
) -> list[dict[str, Any]]:
    if not path.exists():
        raise FileNotFoundError(f"Salary seed CSV not found: {path}")
    sanity_needs_review_by_role_id = load_sanity_needs_review(sanity_review_path)
    with path.open(newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        rows = list(reader)

    payloads = [
        role_salary_payload_from_seed_row(
            row,
            region_override=region_override,
            sanity_needs_review_by_role_id=sanity_needs_review_by_role_id,
        )
        for row in rows
    ]
    seen_primary_keys: set[tuple[int, str]] = set()
    duplicates: list[tuple[int, str]] = []
    for payload in payloads:
        primary_key = (
            int(payload["role_id"]),
            str(payload["region"]),
        )
        if primary_key in seen_primary_keys:
            duplicates.append(primary_key)
        seen_primary_keys.add(primary_key)
    if duplicates:
        sample = ", ".join(
            f"(role_id={role_id}, region={region})"
            for role_id, region in duplicates[:5]
        )
        raise ValueError(f"Duplicate role_salaries primary keys in seed CSV: {sample}")
    return payloads


def load_sanity_needs_review(path: Path | None) -> dict[str, bool] | None:
    if path is None or not path.exists():
        return None
    with path.open(newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        required_columns = {"role_id", "sanity_status"}
        missing_columns = required_columns - set(reader.fieldnames or [])
        if missing_columns:
            raise ValueError(
                "Sanity review CSV is missing required columns: "
                + ", ".join(sorted(missing_columns))
            )
        return {
            str(parse_required_int(row.get("role_id"), "role_id")): (
                collapse_spaces(row.get("sanity_status") or "")
                != "acceptable_for_class_project"
            )
            for row in reader
        }


def parse_optional_bool(value: Any) -> bool:
    text = collapse_spaces(str(value or "")).casefold()
    if not text:
        return False
    if text in {"true", "t", "yes", "y", "1"}:
        return True
    if text in {"false", "f", "no", "n", "0"}:
        return False
    raise ValueError(f"Could not parse boolean value '{text}'.")


def parse_required_int(value: Any, field_name: str) -> int:
    parsed = parse_optional_float(value)
    if parsed is None:
        raise ValueError(f"Missing required integer field: {field_name}")
    return int(parsed)


def parse_optional_float(value: Any) -> float | None:
    if value is None:
        return None
    text = collapse_spaces(str(value))
    if not text:
        return None
    normalized = text.replace(".", "").replace(",", ".") if "," in text else text
    try:
        return float(normalized)
    except ValueError as error:
        raise ValueError(f"Could not parse numeric value '{text}'.") from error


def optional_text(value: Any) -> str | None:
    text = collapse_spaces(str(value or ""))
    return text or None


def collapse_spaces(value: str) -> str:
    return " ".join(value.strip().split())


def normalize_supabase_url(value: str) -> str:
    parsed = urllib.parse.urlparse(value.strip())
    if not parsed.scheme or not parsed.netloc:
        raise ValueError(
            "SUPABASE_URL must be a full URL, such as "
            "https://your-project-ref.supabase.co"
        )
    dashboard_prefix = "/dashboard/project/"
    if parsed.netloc == "supabase.com" and parsed.path.startswith(dashboard_prefix):
        project_ref = parsed.path[len(dashboard_prefix) :].split("/", 1)[0]
        if project_ref:
            return f"https://{project_ref}.supabase.co"
    return value.strip().rstrip("/")


def load_dotenv_file(path: Path) -> None:
    if not path.exists():
        return
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        name, value = line.split("=", 1)
        name = name.strip()
        value = value.strip()
        if not name or name in os.environ:
            continue
        if (
            (value.startswith('"') and value.endswith('"'))
            or (value.startswith("'") and value.endswith("'"))
        ):
            value = value[1:-1]
        os.environ[name] = value


def get_required_supabase_env() -> tuple[str, str]:
    load_dotenv_file(Path(".env"))
    supabase_url = os.getenv("SUPABASE_URL", "").strip()
    service_role_key = os.getenv("SUPABASE_SERVICE_ROLE_KEY", "").strip()
    missing = []
    if not supabase_url:
        missing.append("SUPABASE_URL")
    if not service_role_key:
        missing.append("SUPABASE_SERVICE_ROLE_KEY")
    if missing:
        raise ValueError(f"Missing required environment variables: {', '.join(missing)}")
    return normalize_supabase_url(supabase_url), service_role_key


class SupabaseRestClient:
    def __init__(self, supabase_url: str, service_role_key: str):
        self.supabase_url = supabase_url.rstrip("/")
        self.service_role_key = service_role_key

    def validate_role_salaries_schema(self) -> list[str]:
        status, _, body = self.request(
            "GET",
            "/rest/v1/?select=redacted",
            include_api_key_query=False,
        )
        if not (200 <= status < 300):
            raise SupabaseError(
                f"Could not read Supabase OpenAPI schema: HTTP {status}."
            )
        payload = json.loads(body)
        columns = list(
            payload.get("definitions", {})
            .get("role_salaries", {})
            .get("properties", {})
            .keys()
        )
        missing = [column for column in ROLE_SALARIES_COLUMNS if column not in columns]
        if missing:
            raise SupabaseError(
                "role_salaries is missing required columns: "
                + ", ".join(missing)
            )
        return columns

    def count_role_salaries(self, region: str = "") -> int:
        params: dict[str, str] = {
            "select": "role_id",
            "limit": "1",
        }
        if region:
            params["region"] = f"eq.{region}"
        status, headers, body = self.request(
            "GET",
            "/rest/v1/role_salaries?" + urllib.parse.urlencode(params),
            extra_headers={"Prefer": "count=exact"},
        )
        if not (200 <= status < 300):
            raise SupabaseError(format_supabase_error("GET", "role_salaries", status, body))
        content_range = headers.get("Content-Range") or headers.get("content-range") or ""
        if "/" in content_range:
            total_text = content_range.rsplit("/", 1)[1]
            if total_text.isdigit():
                return int(total_text)
        rows = json.loads(body)
        return len(rows) if isinstance(rows, list) else 0

    def upsert_role_salaries(
        self,
        rows: Sequence[Mapping[str, Any]],
        batch_size: int = DEFAULT_BATCH_SIZE,
    ) -> int:
        rows_upserted = 0
        for start in range(0, len(rows), batch_size):
            batch = list(rows[start : start + batch_size])
            params = urllib.parse.urlencode(
                {"on_conflict": "role_id,region"},
                safe=",",
            )
            status, _, body = self.request(
                "POST",
                f"/rest/v1/role_salaries?{params}",
                payload=batch,
                extra_headers={
                    "Prefer": "resolution=merge-duplicates,return=minimal",
                },
            )
            if not (200 <= status < 300):
                raise SupabaseError(
                    format_supabase_error("POST", "role_salaries", status, body)
                )
            rows_upserted += len(batch)
        return rows_upserted

    def request(
        self,
        method: str,
        path: str,
        payload: Any | None = None,
        extra_headers: Mapping[str, str] | None = None,
        include_api_key_query: bool = True,
    ) -> tuple[int, Mapping[str, str], str]:
        headers = {
            "apikey": self.service_role_key,
            "Authorization": f"Bearer {self.service_role_key}",
            "Accept": "application/json",
        }
        if payload is not None:
            headers["Content-Type"] = "application/json"
        if extra_headers:
            headers.update(extra_headers)
        body = None
        if payload is not None:
            body = json.dumps(payload).encode("utf-8")
        request = urllib.request.Request(
            self.supabase_url + path,
            data=body,
            headers=headers,
            method=method,
        )
        try:
            with urllib.request.urlopen(request, timeout=60) as response:
                return (
                    response.status,
                    dict(response.headers),
                    response.read().decode("utf-8", errors="replace"),
                )
        except urllib.error.HTTPError as error:
            return (
                error.code,
                dict(error.headers),
                error.read().decode("utf-8", errors="replace"),
            )
        except urllib.error.URLError as error:
            raise SupabaseError(f"Supabase request failed: {error.reason}") from error


def format_supabase_error(
    method: str,
    table: str,
    status_code: int,
    body: str,
) -> str:
    detail = body[:500] if body else "No response body returned."
    return f"Supabase {method} failed for table '{table}' with HTTP {status_code}: {detail}"


def summarize_payloads(payloads: Sequence[Mapping[str, Any]]) -> tuple[
    collections.Counter[str],
    collections.Counter[str],
]:
    region_counts = collections.Counter(str(row["region"]) for row in payloads)
    needs_review_counts = collections.Counter(
        "true" if row["needs_review"] else "false" for row in payloads
    )
    return region_counts, needs_review_counts


def print_summary(stats: ImportStats) -> None:
    print(f"CSV rows read: {stats.csv_rows_read}")
    print(f"Payload rows prepared: {stats.payload_rows}")
    print(f"Rows upserted: {stats.rows_upserted}")
    print(f"Rows currently in role_salaries for imported region: {stats.rows_after_import}")
    print("Count by region:")
    for region, count in sorted(stats.region_counts.items()):
        print(f"  {region}: {count}")
    print("Count by needs_review:")
    for value, count in sorted(stats.needs_review_counts.items()):
        print(f"  {value}: {count}")
    if stats.sanity_review_path is not None:
        print(f"Sanity review override: {stats.sanity_review_path}")
    print(f"Dry run: {'yes' if stats.dry_run else 'no'}")


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "One-time database population: import Phase 8 German salary seed "
            "rows into role_salaries."
        ),
    )
    parser.add_argument(
        "--csv",
        type=Path,
        default=DEFAULT_SEED,
        help="Salary seed CSV to import.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate and summarize the import without writing to Supabase.",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=DEFAULT_BATCH_SIZE,
        help=f"Supabase REST upsert batch size. Defaults to {DEFAULT_BATCH_SIZE}.",
    )
    parser.add_argument(
        "--region",
        help="Override region for every imported row, e.g. DE.",
    )
    parser.add_argument(
        "--sanity-review",
        type=Path,
        default=DEFAULT_SANITY_REVIEW,
        help=(
            "Optional sanity review CSV. When present, rows with "
            "sanity_status=acceptable_for_class_project are imported with "
            "needs_review=false; all other sanity statuses stay true."
        ),
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_arg_parser()
    args = parser.parse_args(argv)
    if args.batch_size < 1:
        parser.error("--batch-size must be greater than zero.")
    try:
        payloads = load_seed_payloads(
            args.csv,
            region_override=args.region or "",
            sanity_review_path=args.sanity_review,
        )
        region_counts, needs_review_counts = summarize_payloads(payloads)
        rows_upserted = 0
        rows_after_import = 0
        if not args.dry_run:
            supabase_url, service_role_key = get_required_supabase_env()
            client = SupabaseRestClient(supabase_url, service_role_key)
            client.validate_role_salaries_schema()
            rows_upserted = client.upsert_role_salaries(
                payloads,
                batch_size=args.batch_size,
            )
            first_region = next(iter(region_counts)) if len(region_counts) == 1 else ""
            rows_after_import = client.count_role_salaries(
                region=first_region,
            )
        stats = ImportStats(
            csv_rows_read=len(payloads),
            payload_rows=len(payloads),
            rows_upserted=rows_upserted,
            rows_after_import=rows_after_import,
            region_counts=region_counts,
            needs_review_counts=needs_review_counts,
            sanity_review_path=(
                args.sanity_review if args.sanity_review and args.sanity_review.exists() else None
            ),
            dry_run=args.dry_run,
        )
        print_summary(stats)
        return 0
    except (FileNotFoundError, ValueError, SupabaseError, csv.Error) as error:
        print(f"Error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
