#!/usr/bin/env python3
"""Create review decisions and proposed overrides for Phase 7 salary seeds.

This helper is intentionally local and non-mutating. It reads the generated
salary seed and sanity-review CSVs, classifies rows into review decisions, and
writes proposed manual overrides that can be inspected before Phase 8. It never
reads from or writes to Supabase.
"""

from __future__ import annotations

import argparse
import collections
import csv
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence


DEFAULT_SEED = Path("data/german_salary_seed.autogenerated.csv")
DEFAULT_SANITY_REVIEW = Path("data/german_salary_seed_sanity_review.csv")
DEFAULT_DECISIONS_OUTPUT = Path("data/german_salary_seed_review_decisions.csv")
DEFAULT_OVERRIDES_OUTPUT = Path("data/german_salary_overrides.proposed.csv")

SANITY_FIELDNAMES = [
    "role_id",
    "job_title",
    "domain_tags",
    "kldb_code",
    "entgeltatlas_match_title",
    "salary_group_code",
    "salary_source_group_title",
    "salary_selected_column",
    "salary_median_monthly_gross_eur",
    "annualized_salary_eur",
    "salary_band",
    "match_confidence",
    "source_status",
    "existing_needs_review",
    "sanity_status",
    "sanity_flags",
    "recommended_action",
    "sanity_notes",
    "benchmark_context",
]

DECISION_FIELDNAMES = [
    "role_id",
    "job_title",
    "domain_tags",
    "current_kldb_code",
    "current_match_title",
    "current_salary_monthly_gross_eur",
    "current_salary_band",
    "salary_group_code",
    "salary_source_group_title",
    "salary_selected_column",
    "match_confidence",
    "source_status",
    "sanity_status",
    "sanity_flags",
    "review_decision",
    "proposed_action",
    "proposed_kldb_code",
    "proposed_match_title",
    "proposed_salary_median_monthly_gross_eur",
    "proposed_salary_median_display",
    "proposed_salary_band",
    "proposed_salary_score",
    "proposed_match_confidence",
    "override_reason",
    "override_notes",
    "benchmark_context",
]

OVERRIDE_FIELDNAMES = [
    "role_id",
    "job_title",
    "kldb_code",
    "entgeltatlas_match_title",
    "salary_median_monthly_gross_eur",
    "salary_median_display",
    "salary_low_monthly_gross_eur",
    "salary_high_monthly_gross_eur",
    "salary_value_capped",
    "salary_band",
    "salary_score",
    "match_confidence",
    "notes",
]

RESEARCH_FLAGS = {
    "creative_mapping_questionable",
    "electrical_group_questionable",
    "low_match_confidence",
    "potentially_unrelated_group",
}


@dataclass(frozen=True)
class ReviewDecision:
    role_id: str
    job_title: str
    domain_tags: str
    current_kldb_code: str
    current_match_title: str
    current_salary_monthly_gross_eur: int | None
    current_salary_band: str
    salary_group_code: str
    salary_source_group_title: str
    salary_selected_column: str
    match_confidence: str
    source_status: str
    sanity_status: str
    sanity_flags: tuple[str, ...]
    review_decision: str
    proposed_action: str
    proposed_kldb_code: str = ""
    proposed_match_title: str = ""
    proposed_salary_median_monthly_gross_eur: int | None = None
    proposed_salary_median_display: str = ""
    proposed_salary_band: str = ""
    proposed_salary_score: int | None = None
    proposed_match_confidence: str = ""
    override_reason: str = ""
    override_notes: str = ""
    benchmark_context: str = ""


def required_seed_fields() -> list[str]:
    return [
        "role_id",
        "job_title",
        "domain_tags",
        "kldb_code",
        "entgeltatlas_match_title",
        "salary_group_code",
        "salary_source_group_title",
        "salary_selected_column",
        "salary_median_monthly_gross_eur",
        "salary_fachkraefte_monthly_gross_eur",
        "salary_spezialisten_monthly_gross_eur",
        "salary_experten_monthly_gross_eur",
        "salary_band",
        "salary_score",
        "match_confidence",
        "source_status",
        "needs_review",
    ]


def review_seed_row(
    seed_row: Mapping[str, str],
    sanity_row: Mapping[str, str] | None = None,
) -> ReviewDecision:
    sanity_row = sanity_row or {}
    flags = parse_flags(sanity_row.get("sanity_flags", ""))
    base = base_decision(seed_row, sanity_row, flags)

    if not flags and sanity_row.get("sanity_status") in {
        "",
        "acceptable_for_class_project",
    }:
        return with_decision(
            base,
            review_decision="approve",
            proposed_action="keep_current",
            override_reason="No automated sanity flags were raised.",
        )

    if set(flags) & RESEARCH_FLAGS:
        return with_decision(
            base,
            review_decision="manual_research_required",
            proposed_action="find_better_kldb_mapping",
            override_reason="Mapping confidence or occupational group is too uncertain for an automated salary-level override.",
        )

    if "junior_salary_likely_high" in flags:
        override = salary_level_override(
            base,
            seed_row,
            target_level="fachkraefte",
            reason=(
                "Junior/entry title received a Spezialisten/Experten aggregate; "
                "propose the Fachkräfte salary from the same BA salary group."
            ),
        )
        if override is not None:
            return override

    if (
        "senior_salary_likely_low" in flags
        and "non_core_it_salary_group" not in flags
    ):
        override = salary_level_override(
            base,
            seed_row,
            target_level="experten",
            reason=(
                "Senior/manager/architect title received a lower aggregate; "
                "propose the Experten salary from the same BA salary group."
            ),
        )
        if override is not None:
            return override

    if should_lower_security_expert(seed_row, flags):
        override = salary_level_override(
            base,
            seed_row,
            target_level="spezialisten",
            reason=(
                "Security analyst/admin title received an Experten aggregate; "
                "propose the Spezialisten salary from the same BA salary group."
            ),
        )
        if override is not None:
            return override

    if sanity_row.get("sanity_status") == "manual_override_recommended":
        return with_decision(
            base,
            review_decision="manual_research_required",
            proposed_action="review_manually",
            override_reason="The row is flagged for manual review but no deterministic salary-level override is safe.",
        )

    return with_decision(
        base,
        review_decision="needs_human_review",
        proposed_action="review_current_ba_aggregate",
        override_reason="The row is plausible as a BA aggregate but should be checked before Phase 8.",
    )


def base_decision(
    seed_row: Mapping[str, str],
    sanity_row: Mapping[str, str],
    flags: tuple[str, ...],
) -> ReviewDecision:
    return ReviewDecision(
        role_id=value(seed_row, "role_id"),
        job_title=value(seed_row, "job_title"),
        domain_tags=value(seed_row, "domain_tags"),
        current_kldb_code=value(seed_row, "kldb_code"),
        current_match_title=value(seed_row, "entgeltatlas_match_title"),
        current_salary_monthly_gross_eur=parse_int(
            seed_row.get("salary_median_monthly_gross_eur")
        ),
        current_salary_band=value(seed_row, "salary_band"),
        salary_group_code=value(seed_row, "salary_group_code"),
        salary_source_group_title=value(seed_row, "salary_source_group_title"),
        salary_selected_column=value(seed_row, "salary_selected_column"),
        match_confidence=value(seed_row, "match_confidence"),
        source_status=value(seed_row, "source_status"),
        sanity_status=value(sanity_row, "sanity_status"),
        sanity_flags=flags,
        review_decision="needs_human_review",
        proposed_action="review_current_ba_aggregate",
        benchmark_context=value(sanity_row, "benchmark_context"),
    )


def with_decision(
    decision: ReviewDecision,
    review_decision: str,
    proposed_action: str,
    override_reason: str,
    override_notes: str = "",
) -> ReviewDecision:
    return ReviewDecision(
        **{
            **decision.__dict__,
            "review_decision": review_decision,
            "proposed_action": proposed_action,
            "override_reason": override_reason,
            "override_notes": override_notes,
        }
    )


LEVEL_CONFIG = {
    "fachkraefte": {
        "digit": "2",
        "column": "Fachkräfte",
        "field": "salary_fachkraefte_monthly_gross_eur",
        "action": "use_fachkraefte_level",
    },
    "spezialisten": {
        "digit": "3",
        "column": "Spezialisten",
        "field": "salary_spezialisten_monthly_gross_eur",
        "action": "use_spezialisten_level",
    },
    "experten": {
        "digit": "4",
        "column": "Experten",
        "field": "salary_experten_monthly_gross_eur",
        "action": "use_experten_level",
    },
}


def salary_level_override(
    decision: ReviewDecision,
    seed_row: Mapping[str, str],
    target_level: str,
    reason: str,
) -> ReviewDecision | None:
    config = LEVEL_CONFIG[target_level]
    proposed_salary = parse_int(seed_row.get(config["field"]))
    if proposed_salary is None:
        return None
    proposed_code = replace_kldb_level_digit(
        decision.current_kldb_code,
        str(config["digit"]),
    )
    band, score = salary_band_and_score(proposed_salary, False)
    notes = (
        f"{reason} Current value was "
        f"{format_optional_int(decision.current_salary_monthly_gross_eur)} EUR/month "
        f"from {decision.salary_selected_column}; proposed value is "
        f"{proposed_salary} EUR/month from {config['column']}."
    )
    return ReviewDecision(
        **{
            **decision.__dict__,
            "review_decision": "propose_salary_level_override",
            "proposed_action": str(config["action"]),
            "proposed_kldb_code": proposed_code,
            "proposed_match_title": decision.current_match_title,
            "proposed_salary_median_monthly_gross_eur": proposed_salary,
            "proposed_salary_median_display": str(proposed_salary),
            "proposed_salary_band": band,
            "proposed_salary_score": score,
            "proposed_match_confidence": decision.match_confidence,
            "override_reason": reason,
            "override_notes": notes,
        }
    )


def should_lower_security_expert(
    seed_row: Mapping[str, str],
    flags: tuple[str, ...],
) -> bool:
    title = value(seed_row, "job_title").casefold()
    selected_column = value(seed_row, "salary_selected_column")
    if "security_expert_salary_high" not in flags:
        return False
    if selected_column != "Experten":
        return False
    return bool(
        re.search(
            r"\b(admin|administrator|analyst|support|operator|technician)\b",
            title,
        )
    )


def override_from_decision(decision: ReviewDecision) -> dict[str, str]:
    if (
        decision.review_decision != "propose_salary_level_override"
        or decision.proposed_salary_median_monthly_gross_eur is None
    ):
        return {}
    return {
        "role_id": decision.role_id,
        "job_title": "",
        "kldb_code": decision.proposed_kldb_code,
        "entgeltatlas_match_title": decision.proposed_match_title,
        "salary_median_monthly_gross_eur": str(
            decision.proposed_salary_median_monthly_gross_eur
        ),
        "salary_median_display": decision.proposed_salary_median_display,
        "salary_low_monthly_gross_eur": "",
        "salary_high_monthly_gross_eur": "",
        "salary_value_capped": "false",
        "salary_band": decision.proposed_salary_band,
        "salary_score": "" if decision.proposed_salary_score is None else str(decision.proposed_salary_score),
        "match_confidence": decision.proposed_match_confidence,
        "notes": decision.override_notes,
    }


def decision_to_row(decision: ReviewDecision) -> dict[str, str]:
    return {
        "role_id": decision.role_id,
        "job_title": decision.job_title,
        "domain_tags": decision.domain_tags,
        "current_kldb_code": decision.current_kldb_code,
        "current_match_title": decision.current_match_title,
        "current_salary_monthly_gross_eur": format_optional_int(
            decision.current_salary_monthly_gross_eur
        ),
        "current_salary_band": decision.current_salary_band,
        "salary_group_code": decision.salary_group_code,
        "salary_source_group_title": decision.salary_source_group_title,
        "salary_selected_column": decision.salary_selected_column,
        "match_confidence": decision.match_confidence,
        "source_status": decision.source_status,
        "sanity_status": decision.sanity_status,
        "sanity_flags": ";".join(decision.sanity_flags),
        "review_decision": decision.review_decision,
        "proposed_action": decision.proposed_action,
        "proposed_kldb_code": decision.proposed_kldb_code,
        "proposed_match_title": decision.proposed_match_title,
        "proposed_salary_median_monthly_gross_eur": format_optional_int(
            decision.proposed_salary_median_monthly_gross_eur
        ),
        "proposed_salary_median_display": decision.proposed_salary_median_display,
        "proposed_salary_band": decision.proposed_salary_band,
        "proposed_salary_score": (
            "" if decision.proposed_salary_score is None else str(decision.proposed_salary_score)
        ),
        "proposed_match_confidence": decision.proposed_match_confidence,
        "override_reason": decision.override_reason,
        "override_notes": decision.override_notes,
        "benchmark_context": decision.benchmark_context,
    }


def build_review_outputs(
    seed_rows: Sequence[Mapping[str, str]],
    sanity_rows: Sequence[Mapping[str, str]],
) -> tuple[list[dict[str, str]], list[dict[str, str]], list[ReviewDecision]]:
    sanity_by_role_id = {value(row, "role_id"): row for row in sanity_rows}
    decisions = [
        review_seed_row(seed_row, sanity_by_role_id.get(value(seed_row, "role_id")))
        for seed_row in seed_rows
    ]
    decision_rows = [decision_to_row(decision) for decision in decisions]
    overrides = [
        override
        for decision in decisions
        for override in [override_from_decision(decision)]
        if override
    ]
    return decision_rows, overrides, decisions


def parse_flags(value_text: str) -> tuple[str, ...]:
    return tuple(
        flag.strip()
        for flag in value_text.split(";")
        if flag.strip()
    )


def replace_kldb_level_digit(kldb_code: str, level_digit: str) -> str:
    normalized = re.sub(r"\D", "", kldb_code or "")
    if len(normalized) >= 5:
        return normalized[:4] + level_digit + normalized[5:]
    if len(normalized) == 4:
        return normalized + level_digit
    return normalized


def salary_band_and_score(
    salary_median_monthly_gross_eur: int | None,
    salary_value_capped: bool,
) -> tuple[str, int]:
    if salary_value_capped:
        return "capped", 5
    if salary_median_monthly_gross_eur is None:
        return "unknown", 0
    if salary_median_monthly_gross_eur < 4000:
        return "low", 1
    if salary_median_monthly_gross_eur < 5500:
        return "medium", 2
    if salary_median_monthly_gross_eur < 7000:
        return "high", 3
    return "very_high", 4


def parse_int(value_text: Any) -> int | None:
    if value_text is None:
        return None
    text = str(value_text).strip()
    if not text:
        return None
    match = re.search(r"\d+", text.replace(".", "").replace(",", ""))
    if not match:
        return None
    return int(match.group(0))


def format_optional_int(value_int: int | None) -> str:
    return "" if value_int is None else str(value_int)


def value(row: Mapping[str, str], field: str) -> str:
    return str(row.get(field) or "").strip()


def read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        raise FileNotFoundError(f"CSV not found: {path}")
    with path.open(newline="", encoding="utf-8-sig") as handle:
        return [dict(row) for row in csv.DictReader(handle)]


def write_csv(
    path: Path,
    rows: Sequence[Mapping[str, str]],
    fieldnames: Sequence[str],
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(fieldnames), extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, "") for field in fieldnames})


def print_summary(
    decisions: Sequence[ReviewDecision],
    overrides: Sequence[Mapping[str, str]],
    output: Path,
    overrides_output: Path,
) -> None:
    decision_counts = collections.Counter(
        decision.review_decision for decision in decisions
    )
    action_counts = collections.Counter(decision.proposed_action for decision in decisions)
    print(f"Rows reviewed: {len(decisions)}")
    print("Count by review_decision:")
    for decision, count in sorted(decision_counts.items()):
        print(f"  {decision}: {count}")
    print("Count by proposed_action:")
    for action, count in sorted(action_counts.items()):
        print(f"  {action}: {count}")
    print(f"Proposed manual overrides: {len(overrides)}")
    print(f"Review decisions CSV path: {output}")
    print(f"Proposed overrides CSV path: {overrides_output}")
    print("No Supabase writes were made; this helper only writes local CSV artifacts.")


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate Phase 7 salary review decisions and proposed overrides.",
    )
    parser.add_argument(
        "--seed",
        type=Path,
        default=DEFAULT_SEED,
        help="Path to data/german_salary_seed.autogenerated.csv.",
    )
    parser.add_argument(
        "--sanity-review",
        type=Path,
        default=DEFAULT_SANITY_REVIEW,
        help="Path to data/german_salary_seed_sanity_review.csv.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_DECISIONS_OUTPUT,
        help="Path for review decisions CSV.",
    )
    parser.add_argument(
        "--overrides-output",
        type=Path,
        default=DEFAULT_OVERRIDES_OUTPUT,
        help="Path for proposed manual overrides CSV.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_arg_parser()
    args = parser.parse_args(argv)
    try:
        seed_rows = read_csv(args.seed)
        sanity_rows = read_csv(args.sanity_review)
        decision_rows, overrides, decisions = build_review_outputs(
            seed_rows,
            sanity_rows,
        )
        write_csv(args.output, decision_rows, DECISION_FIELDNAMES)
        write_csv(args.overrides_output, overrides, OVERRIDE_FIELDNAMES)
        print_summary(decisions, overrides, args.output, args.overrides_output)
        return 0
    except (FileNotFoundError, csv.Error, ValueError) as error:
        print(f"Error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
