create extension if not exists vector with schema extensions;

create table if not exists public.certifications (
  certification_id bigint generated by default as identity primary key,
  certification_name text not null,
  normalized_certification_name text not null,
  embedding extensions.vector
);

create unique index if not exists certifications_normalized_certification_name_key
  on public.certifications (normalized_certification_name);

create index if not exists certifications_certification_name_idx
  on public.certifications (certification_name);

create table if not exists public.certifications_mapping (
  role_id bigint not null references public.career_roles(role_id) on delete cascade,
  certification_id bigint not null
    references public.certifications(certification_id) on delete cascade,
  primary key (role_id, certification_id)
);

create index if not exists certifications_mapping_certification_id_idx
  on public.certifications_mapping (certification_id);

do $$
begin
  if to_regclass('public.role_certifications') is not null then
    insert into public.certifications (
      certification_name,
      normalized_certification_name
    )
    select distinct on (normalized_certification_name)
      certification_name,
      normalized_certification_name
    from public.role_certifications
    where normalized_certification_name is not null
      and normalized_certification_name <> ''
    order by normalized_certification_name, certification_name
    on conflict (normalized_certification_name) do update
      set certification_name = excluded.certification_name;

    insert into public.certifications_mapping (
      role_id,
      certification_id
    )
    select distinct
      role_certification.role_id,
      certification.certification_id
    from public.role_certifications as role_certification
    join public.certifications as certification
      on certification.normalized_certification_name =
        role_certification.normalized_certification_name
    on conflict do nothing;
  end if;
end $$;

alter table public.certifications enable row level security;
alter table public.certifications_mapping enable row level security;

revoke all on table public.certifications from anon, authenticated;
revoke all on table public.certifications_mapping from anon, authenticated;

grant select, insert, update, delete on table public.certifications to service_role;
grant select, insert, update, delete
  on table public.certifications_mapping to service_role;

do $$
declare
  certification_sequence text;
begin
  certification_sequence := pg_get_serial_sequence(
    'public.certifications',
    'certification_id'
  );

  if certification_sequence is not null then
    execute format(
      'grant usage, select on sequence %s to service_role',
      certification_sequence
    );
  end if;
end $$;

drop table if exists public.role_certifications;
