create extension if not exists vector with schema extensions;

create table if not exists public.career_roles (
  role_id bigint generated by default as identity primary key,
  job_title text not null,
  job_description text,
  raw_skills text,
  raw_certifications text,
  source_row_hash text,
  domain_tags text
);

create table if not exists public.role_skills (
  role_id bigint not null references public.career_roles(role_id) on delete cascade,
  skill_name text not null,
  normalized_skill_name text not null,
  primary key (role_id, normalized_skill_name)
);

create table if not exists public.role_certifications (
  role_id bigint not null references public.career_roles(role_id) on delete cascade,
  certification_name text not null,
  primary key (role_id, certification_name)
);

create table if not exists public.esco_occupations (
  esco_uri text primary key,
  isco_code text,
  name text,
  definition text
);

create table if not exists public.esco_mappings (
  role_id bigint primary key references public.career_roles(role_id) on delete cascade,
  esco_uri text not null references public.esco_occupations(esco_uri) on delete cascade,
  esco_title text,
  match_score numeric
);

create table if not exists public.role_salaries (
  role_id bigint not null references public.career_roles(role_id) on delete cascade,
  salary_band text,
  salary_score double precision,
  salary_median_monthly_gross_eur numeric(12,2),
  region text not null default 'DE',
  entgeltatlas_match_title text,
  confidence double precision,
  needs_review boolean not null default false,
  match_confidence text,
  kldb_code text,
  primary key (role_id, region)
);

create index if not exists career_roles_domain_tags_idx
  on public.career_roles (domain_tags);

create unique index if not exists career_roles_source_row_hash_key
  on public.career_roles (source_row_hash)
  where source_row_hash is not null;

create index if not exists role_skills_normalized_skill_name_idx
  on public.role_skills (normalized_skill_name);

create index if not exists role_certifications_certification_name_idx
  on public.role_certifications (certification_name);

create index if not exists esco_occupations_isco_code_idx
  on public.esco_occupations (isco_code);

create index if not exists esco_mappings_esco_uri_idx
  on public.esco_mappings (esco_uri);

create index if not exists role_salaries_region_idx
  on public.role_salaries (region);

alter table public.career_roles enable row level security;
alter table public.role_skills enable row level security;
alter table public.role_certifications enable row level security;
alter table public.esco_occupations enable row level security;
alter table public.esco_mappings enable row level security;
alter table public.role_salaries enable row level security;

revoke all on table public.career_roles from anon, authenticated;
revoke all on table public.role_skills from anon, authenticated;
revoke all on table public.role_certifications from anon, authenticated;
revoke all on table public.esco_occupations from anon, authenticated;
revoke all on table public.esco_mappings from anon, authenticated;
revoke all on table public.role_salaries from anon, authenticated;

grant select, insert, update, delete on table public.career_roles to service_role;
grant select, insert, update, delete on table public.role_skills to service_role;
grant select, insert, update, delete on table public.role_certifications to service_role;
grant select, insert, update, delete on table public.esco_occupations to service_role;
grant select, insert, update, delete on table public.esco_mappings to service_role;
grant select, insert, update, delete on table public.role_salaries to service_role;

grant usage, select on sequence public.career_roles_role_id_seq to service_role;
