import { create } from "zustand";
import {
  ApiError,
  getCareerPath,
  matchRoles,
  parseCv,
  submitManualCv,
  type CareerPathReport,
  type CVData,
  type RoleMatch,
} from "@/lib/api";
import {
  applyEditsToCvData,
  cvDataToRecapEdits,
  cvDataToUserCareerProfile,
  fallbackIdentity,
  manualFormToInput,
  toConfirmedCvData,
  type RecapEdits,
} from "@/lib/cvData";
import type {
  AnalyzedSkill,
  CertificationItem,
  EducationItem,
  ExperienceItem,
  Identity,
  ManualProfileForm,
  ProjectItem,
} from "@/types";
import { emptyManualProfileForm } from "@/types";

export type Stage = "entry" | "recap" | "matching" | "directions" | "preparing_paths" | "focus";

export const MAX_PICKS = 3;
function errorMessage(err: unknown, fallback: string): string {
  if (err instanceof ApiError) return err.message;
  if (err instanceof Error) return err.message;
  return fallback;
}

type Store = {
  stage: Stage;
  setStage: (s: Stage) => void;

  /** Canonical parsed/assembled CV (source of truth sent to the backend). */
  cvData: CVData | null;

  /** Editable recap projections seeded from `cvData`. */
  skills: AnalyzedSkill[];
  addSkill: (name: string, confidence?: number) => void;
  removeSkill: (name: string) => void;

  interests: string[];
  addInterest: (name: string) => void;
  removeInterest: (name: string) => void;

  experiences: ExperienceItem[];
  addExperience: (e: ExperienceItem) => void;
  removeExperience: (idx: number) => void;

  educations: EducationItem[];
  addEducation: (e: EducationItem) => void;
  removeEducation: (idx: number) => void;

  certifications: CertificationItem[];
  addCertification: (c: CertificationItem) => void;
  removeCertification: (idx: number) => void;

  projects: ProjectItem[];
  addProject: (p: ProjectItem) => void;
  removeProject: (idx: number) => void;

  /** Career identity generated by the aggregate profile pipeline. */
  identity: Identity | null;
  setIdentityLead: (lead: string) => void;

  /** Role matching results. */
  roleMatches: RoleMatch[];
  selectedRoleIds: string[];
  toggleSelectedRole: (id: string) => void;

  careerPathReports: Record<string, CareerPathReport>;
  careerPathLoading: Record<string, boolean>;
  careerPathErrors: Record<string, string | null>;

  /** Async status for the current network action. */
  error: string | null;
  manualDraft: ManualProfileForm;
  setManualDraft: (draft: ManualProfileForm) => void;

  /** Async actions. */
  uploadCv: (file: File) => Promise<boolean>;
  submitManualProfile: (form: ManualProfileForm) => Promise<boolean>;
  runMatching: () => Promise<boolean>;
  loadCareerPath: (roleId: string) => Promise<void>;
  prepareSelectedPaths: (roleIds: string[]) => Promise<void>;
  reset: () => void;
};

function currentEdits(s: Store): RecapEdits {
  return {
    skills: s.skills,
    interests: s.interests,
    experiences: s.experiences,
    educations: s.educations,
    certifications: s.certifications,
    projects: s.projects,
  };
}

/** Build the CVData to send to the backend, merging recap edits into the base. */
function buildOutgoingCvData(s: Store): CVData | null {
  if (!s.cvData) return null;
  return applyEditsToCvData(s.cvData, currentEdits(s));
}

const initialState = {
  stage: "entry" as Stage,
  cvData: null as CVData | null,
  skills: [] as AnalyzedSkill[],
  interests: [] as string[],
  experiences: [] as ExperienceItem[],
  educations: [] as EducationItem[],
  certifications: [] as CertificationItem[],
  projects: [] as ProjectItem[],
  identity: null as Identity | null,

  roleMatches: [] as RoleMatch[],
  selectedRoleIds: [] as string[],

  careerPathReports: {} as Record<string, CareerPathReport>,
  careerPathLoading: {} as Record<string, boolean>,
  careerPathErrors: {} as Record<string, string | null>,
  error: null as string | null,
  manualDraft: emptyManualProfileForm,
};

let matchingRequest: Promise<boolean> | null = null;
let requestGeneration = 0;

export const useStageStore = create<Store>((set, get) => ({
  ...initialState,
  setStage: (stage) => {
    if (stage === "entry" || stage === "recap") {
      requestGeneration += 1;
      matchingRequest = null;
    }
    if (stage === "recap") {
      set({
        stage,
        roleMatches: [],
        selectedRoleIds: [],
        careerPathReports: {},
        careerPathLoading: {},
        careerPathErrors: {},
      });
      return;
    }
    set({ stage });
  },

  addSkill: (name, confidence = 75) =>
    set((s) => {
      const v = name.trim();
      if (!v || s.skills.some((k) => k.name.toLowerCase() === v.toLowerCase())) return s;
      return { skills: [...s.skills, { name: v, confidence }] };
    }),
  removeSkill: (name) => set((s) => ({ skills: s.skills.filter((k) => k.name !== name) })),

  addInterest: (name) =>
    set((s) => {
      const v = name.trim();
      if (!v || s.interests.some((x) => x.toLowerCase() === v.toLowerCase())) return s;
      return { interests: [...s.interests, v] };
    }),
  removeInterest: (name) => set((s) => ({ interests: s.interests.filter((x) => x !== name) })),

  addExperience: (e) => set((s) => ({ experiences: [...s.experiences, e] })),
  removeExperience: (idx) =>
    set((s) => ({ experiences: s.experiences.filter((_, i) => i !== idx) })),

  addEducation: (e) => set((s) => ({ educations: [...s.educations, e] })),
  removeEducation: (idx) => set((s) => ({ educations: s.educations.filter((_, i) => i !== idx) })),

  addCertification: (c) => set((s) => ({ certifications: [...s.certifications, c] })),
  removeCertification: (idx) =>
    set((s) => ({ certifications: s.certifications.filter((_, i) => i !== idx) })),

  addProject: (p) => set((s) => ({ projects: [...s.projects, p] })),
  removeProject: (idx) => set((s) => ({ projects: s.projects.filter((_, i) => i !== idx) })),

  setIdentityLead: (lead) =>
    set((s) => ({
      identity: s.identity
        ? { ...s.identity, lead }
        : { archetype: s.cvData ? fallbackIdentity(s.cvData).archetype : "professional", lead },
      cvData: s.cvData
        ? { ...s.cvData, profile_summary: { ...s.cvData.profile_summary, summary: lead } }
        : null,
    })),
  toggleSelectedRole: (id) =>
    set((s) => {
      if (s.selectedRoleIds.includes(id)) {
        return { selectedRoleIds: s.selectedRoleIds.filter((x) => x !== id) };
      }
      if (s.selectedRoleIds.length >= MAX_PICKS) return s;
      return { selectedRoleIds: [...s.selectedRoleIds, id] };
    }),

  setManualDraft: (manualDraft) => set({ manualDraft }),

  /** Parse an uploaded PDF and seed the recap from the result. */
  uploadCv: async (file) => {
    const generation = ++requestGeneration;
    matchingRequest = null;
    set({
      error: null,
      roleMatches: [],
      selectedRoleIds: [],
      careerPathReports: {},
      careerPathLoading: {},
      careerPathErrors: {},
    });
    try {
      const result = await parseCv(file);
      if (generation !== requestGeneration) return false;
      const identitySummary = result.embedding_profile.career_identity_summary;
      set({
        cvData: result.cv_data,
        identity: {
          archetype: identitySummary.label,
          lead: identitySummary.summary.trim() || fallbackIdentity(result.cv_data).lead,
        },
        ...cvDataToRecapEdits(result.cv_data),
        roleMatches: [],
        selectedRoleIds: [],
        careerPathReports: {},
        careerPathLoading: {},
        careerPathErrors: {},
      });
      return true;
    } catch (err) {
      if (generation !== requestGeneration) return false;
      set({ error: errorMessage(err, "Could not parse the CV.") });
      return false;
    }
  },
  /** Build a CVData from the manual form via the backend and seed the recap. */
  submitManualProfile: async (form) => {
    const generation = ++requestGeneration;
    matchingRequest = null;
    set({
      error: null,
      roleMatches: [],
      selectedRoleIds: [],
      careerPathReports: {},
      careerPathLoading: {},
      careerPathErrors: {},
    });
    try {
      const result = await submitManualCv(manualFormToInput(form));
      if (generation !== requestGeneration) return false;
      const identitySummary = result.embedding_profile.career_identity_summary;
      set({
        cvData: result.cv_data,
        identity: {
          archetype: identitySummary.label,
          lead: identitySummary.summary.trim() || fallbackIdentity(result.cv_data).lead,
        },
        ...cvDataToRecapEdits(result.cv_data),
        roleMatches: [],
        selectedRoleIds: [],
        careerPathReports: {},
        careerPathLoading: {},
        careerPathErrors: {},
      });
      return true;
    } catch (err) {
      if (generation !== requestGeneration) return false;
      set({ error: errorMessage(err, "Could not build the profile.") });
      return false;
    }
  },
  /** Match the edited CV against ESCO roles. */
  runMatching: async () => {
    if (matchingRequest) return matchingRequest;

    const request = (async () => {
      const state = get();
      const outgoing = buildOutgoingCvData(state);
      if (!outgoing) {
        set({ error: "No CV data to match." });
        return false;
      }

      const generation = ++requestGeneration;
      const identity = state.identity ?? fallbackIdentity(outgoing);
      set({
        error: null,
        identity,
        roleMatches: [],
        selectedRoleIds: [],
        careerPathReports: {},
        careerPathLoading: {},
        careerPathErrors: {},
      });
      try {
        const result = await matchRoles(cvDataToUserCareerProfile(outgoing, identity), 9);
        if (generation !== requestGeneration) return false;
        set({
          roleMatches: result.matched_roles,
        });
        return true;
      } catch (err) {
        if (generation !== requestGeneration) return false;
        set({ error: errorMessage(err, "Role matching is unavailable.") });
        return false;
      }
    })();

    const trackedRequest = request.finally(() => {
      if (matchingRequest === trackedRequest) matchingRequest = null;
    });
    matchingRequest = trackedRequest;
    return trackedRequest;
  },
  loadCareerPath: async (roleId) => {
    const state = get();
    if (state.careerPathReports[roleId] || state.careerPathLoading[roleId]) return;
    const outgoing = buildOutgoingCvData(state);
    if (!outgoing) {
      set((s) => ({
        careerPathErrors: { ...s.careerPathErrors, [roleId]: "No CV data to map." },
      }));
      return;
    }

    const generation = requestGeneration;
    set((s) => ({
      careerPathLoading: { ...s.careerPathLoading, [roleId]: true },
      careerPathErrors: { ...s.careerPathErrors, [roleId]: null },
    }));
    try {
      const report = await getCareerPath(roleId, toConfirmedCvData(outgoing, state.identity));
      if (generation !== requestGeneration) return;
      set((s) => ({
        careerPathReports: { ...s.careerPathReports, [roleId]: report },
        careerPathLoading: { ...s.careerPathLoading, [roleId]: false },
      }));
    } catch (err) {
      if (generation !== requestGeneration) return;
      set((s) => ({
        careerPathLoading: { ...s.careerPathLoading, [roleId]: false },
        careerPathErrors: {
          ...s.careerPathErrors,
          [roleId]: errorMessage(err, "Career roadmap is unavailable."),
        },
      }));
    }
  },
  prepareSelectedPaths: async (roleIds) => {
    const selected = [...new Set(roleIds.filter(Boolean))];
    await Promise.allSettled(selected.map((roleId) => get().loadCareerPath(roleId)));
  },
  reset: () => {
    requestGeneration += 1;
    matchingRequest = null;
    set({ ...initialState });
  },
}));
