import { create } from "zustand";
import {
  ApiError,
  getRoleGapAnalysis,
  matchRoles,
  parseCv,
  submitManualCv,
  type CVData,
  type EmbeddingProfile,
  type GapReport,
  type RoleMatch,
} from "@/lib/api";
import {
  applyEditsToCvData,
  cvDataToRecapEdits,
  cvDataToUserCareerProfile,
  fallbackIdentity,
  identityLeadWithTargetPreferences,
  manualFormToInput,
  toConfirmedCvData,
  type RecapEdits,
} from "@/lib/cvData";
import type {
  AnalyzedSkill,
  CertificationItem,
  EducationItem,
  ExperienceItem,
  Identity,
  ManualProfileForm,
  ProjectItem,
} from "@/types";

export type Stage = "entry" | "recap" | "matching" | "directions" | "focus";

export const MAX_PICKS = 3;

function errorMessage(err: unknown, fallback: string): string {
  if (err instanceof ApiError) return err.message;
  if (err instanceof Error) return err.message;
  return fallback;
}

type Store = {
  stage: Stage;
  setStage: (s: Stage) => void;

  /** Canonical parsed/assembled CV (source of truth sent to the backend). */
  cvData: CVData | null;

  /** Editable recap projections seeded from `cvData`. */
  skills: AnalyzedSkill[];
  addSkill: (name: string, confidence?: number) => void;
  removeSkill: (name: string) => void;

  interests: string[];
  addInterest: (name: string) => void;
  removeInterest: (name: string) => void;

  experiences: ExperienceItem[];
  addExperience: (e: ExperienceItem) => void;
  removeExperience: (idx: number) => void;

  educations: EducationItem[];
  addEducation: (e: EducationItem) => void;
  removeEducation: (idx: number) => void;

  certifications: CertificationItem[];
  addCertification: (c: CertificationItem) => void;
  removeCertification: (idx: number) => void;

  projects: ProjectItem[];
  addProject: (p: ProjectItem) => void;
  removeProject: (idx: number) => void;

  /** Career identity generated by the aggregate profile pipeline. */
  identity: Identity | null;
  setIdentityLead: (lead: string) => void;
  identityLoading: boolean;
  embeddingProfile: EmbeddingProfile | null;

  /** Role matching results. */
  roleMatches: RoleMatch[];
  matchAnalysis: string | null;
  selectedRoleIds: string[];
  toggleSelectedRole: (id: string) => void;
  selectedRoleId: string | null;
  setSelectedRoleId: (id: string | null) => void;
  roleGapReports: Record<string, GapReport>;
  roleGapLoading: Record<string, boolean>;
  roleGapErrors: Record<string, string | null>;

  /** Async status for the current network action. */
  loading: boolean;
  error: string | null;
  clearError: () => void;

  /** Async actions. */
  uploadCv: (file: File) => Promise<boolean>;
  submitManualProfile: (form: ManualProfileForm) => Promise<boolean>;
  generateIdentity: () => Promise<void>;
  runMatching: () => Promise<boolean>;
  loadRoleGapAnalysis: (roleId: string) => Promise<void>;
  reset: () => void;
};

function currentEdits(s: Store): RecapEdits {
  return {
    skills: s.skills,
    interests: s.interests,
    experiences: s.experiences,
    educations: s.educations,
    certifications: s.certifications,
    projects: s.projects,
  };
}

/** Build the CVData to send to the backend, merging recap edits into the base. */
function buildOutgoingCvData(s: Store): CVData | null {
  if (!s.cvData) return null;
  return applyEditsToCvData(s.cvData, currentEdits(s));
}

const initialState = {
  stage: "entry" as Stage,
  cvData: null as CVData | null,
  skills: [] as AnalyzedSkill[],
  interests: [] as string[],
  experiences: [] as ExperienceItem[],
  educations: [] as EducationItem[],
  certifications: [] as CertificationItem[],
  projects: [] as ProjectItem[],
  identity: null as Identity | null,
  identityLoading: false,
  embeddingProfile: null as EmbeddingProfile | null,
  roleMatches: [] as RoleMatch[],
  matchAnalysis: null as string | null,
  selectedRoleIds: [] as string[],
  selectedRoleId: null as string | null,
  roleGapReports: {} as Record<string, GapReport>,
  roleGapLoading: {} as Record<string, boolean>,
  roleGapErrors: {} as Record<string, string | null>,
  loading: false,
  error: null as string | null,
};

export const useStageStore = create<Store>((set, get) => ({
  ...initialState,
  setStage: (s) => set({ stage: s }),

  addSkill: (name, confidence = 75) =>
    set((s) => {
      const v = name.trim();
      if (!v || s.skills.some((k) => k.name.toLowerCase() === v.toLowerCase())) return s;
      return { skills: [...s.skills, { name: v, confidence }] };
    }),
  removeSkill: (name) => set((s) => ({ skills: s.skills.filter((k) => k.name !== name) })),

  addInterest: (name) =>
    set((s) => {
      const v = name.trim();
      if (!v || s.interests.some((x) => x.toLowerCase() === v.toLowerCase())) return s;
      return { interests: [...s.interests, v] };
    }),
  removeInterest: (name) => set((s) => ({ interests: s.interests.filter((x) => x !== name) })),

  addExperience: (e) => set((s) => ({ experiences: [...s.experiences, e] })),
  removeExperience: (idx) =>
    set((s) => ({ experiences: s.experiences.filter((_, i) => i !== idx) })),

  addEducation: (e) => set((s) => ({ educations: [...s.educations, e] })),
  removeEducation: (idx) => set((s) => ({ educations: s.educations.filter((_, i) => i !== idx) })),

  addCertification: (c) => set((s) => ({ certifications: [...s.certifications, c] })),
  removeCertification: (idx) =>
    set((s) => ({ certifications: s.certifications.filter((_, i) => i !== idx) })),

  addProject: (p) => set((s) => ({ projects: [...s.projects, p] })),
  removeProject: (idx) => set((s) => ({ projects: s.projects.filter((_, i) => i !== idx) })),

  setIdentityLead: (lead) =>
    set((s) => {
      if (s.identity) return { identity: { ...s.identity, lead } };
      const fallback = s.cvData ? fallbackIdentity(s.cvData) : { archetype: "professional" };
      return { identity: { archetype: fallback.archetype, lead } };
    }),

  toggleSelectedRole: (id) =>
    set((s) => {
      if (s.selectedRoleIds.includes(id)) {
        return { selectedRoleIds: s.selectedRoleIds.filter((x) => x !== id) };
      }
      if (s.selectedRoleIds.length >= MAX_PICKS) return s;
      return { selectedRoleIds: [...s.selectedRoleIds, id] };
    }),

  setSelectedRoleId: (id) => set({ selectedRoleId: id }),
  clearError: () => set({ error: null }),

  /** Parse an uploaded PDF and seed the recap from the result. */
  uploadCv: async (file) => {
    set({ loading: true, error: null });
    try {
      const result = await parseCv(file);
      const identitySummary = result.embedding_profile.career_identity_summary;
      set({
        cvData: result.cv_data,
        embeddingProfile: result.embedding_profile,
        identity: {
          archetype: identitySummary.label,
          lead: identityLeadWithTargetPreferences(result.cv_data, identitySummary.summary),
        },
        ...cvDataToRecapEdits(result.cv_data),
        roleMatches: [],
        matchAnalysis: null,
        selectedRoleIds: [],
        selectedRoleId: null,
        roleGapReports: {},
        roleGapLoading: {},
        roleGapErrors: {},
        loading: false,
      });
      return true;
    } catch (err) {
      set({ loading: false, error: errorMessage(err, "Could not parse the CV.") });
      return false;
    }
  },

  /** Build a CVData from the manual form via the backend and seed the recap. */
  submitManualProfile: async (form) => {
    set({ loading: true, error: null });
    try {
      const result = await submitManualCv(manualFormToInput(form));
      const identitySummary = result.embedding_profile.career_identity_summary;
      set({
        cvData: result.cv_data,
        embeddingProfile: result.embedding_profile,
        identity: {
          archetype: identitySummary.label,
          lead: identityLeadWithTargetPreferences(result.cv_data, identitySummary.summary),
        },
        ...cvDataToRecapEdits(result.cv_data),
        roleMatches: [],
        matchAnalysis: null,
        selectedRoleIds: [],
        selectedRoleId: null,
        roleGapReports: {},
        roleGapLoading: {},
        roleGapErrors: {},
        loading: false,
      });
      return true;
    } catch (err) {
      set({ loading: false, error: errorMessage(err, "Could not build the profile.") });
      return false;
    }
  },

  /** Legacy local fallback; entry pipeline now provides identity before Recap. */
  generateIdentity: async () => {
    const outgoing = buildOutgoingCvData(get());
    if (!outgoing) return;
    set({ identityLoading: true });
    try {
      const result = { starter_identity: fallbackIdentity(outgoing).lead, suggested_questions: [] };
      set({
        identity: {
          archetype: fallbackIdentity(outgoing).archetype,
          lead: identityLeadWithTargetPreferences(outgoing, result.starter_identity),
        },
        identityLoading: false,
      });
    } catch {
      // Identity is non-blocking — fall back to a CV-derived statement.
      set({
        identity: {
          ...fallbackIdentity(outgoing),
          lead: identityLeadWithTargetPreferences(outgoing, fallbackIdentity(outgoing).lead),
        },
        identityLoading: false,
      });
    }
  },

  /** Match the (edited) CV against ESCO roles using the embedding pipeline query text. */
  runMatching: async () => {
    const state = get();
    const outgoing = buildOutgoingCvData(state);
    if (!outgoing) {
      set({ error: "No CV data to match." });
      return false;
    }
    set({ loading: true, error: null, cvData: outgoing });
    try {
      const result = await matchRoles(cvDataToUserCareerProfile(outgoing, state.identity), 9);
      set({
        roleMatches: result.matched_roles,
        matchAnalysis: result.analysis,
        selectedRoleIds: [],
        roleGapReports: {},
        roleGapLoading: {},
        roleGapErrors: {},
        loading: false,
      });
      return true;
    } catch (err) {
      set({ loading: false, error: errorMessage(err, "Role matching is unavailable.") });
      return false;
    }
  },

  loadRoleGapAnalysis: async (roleId) => {
    const state = get();
    if (state.roleGapReports[roleId] || state.roleGapLoading[roleId]) return;
    const outgoing = buildOutgoingCvData(state);
    if (!outgoing) {
      set((s) => ({ roleGapErrors: { ...s.roleGapErrors, [roleId]: "No CV data to analyze." } }));
      return;
    }

    set((s) => ({
      roleGapLoading: { ...s.roleGapLoading, [roleId]: true },
      roleGapErrors: { ...s.roleGapErrors, [roleId]: null },
    }));
    try {
      const report = await getRoleGapAnalysis(roleId, toConfirmedCvData(outgoing));
      set((s) => ({
        roleGapReports: { ...s.roleGapReports, [roleId]: report },
        roleGapLoading: { ...s.roleGapLoading, [roleId]: false },
      }));
    } catch (err) {
      set((s) => ({
        roleGapLoading: { ...s.roleGapLoading, [roleId]: false },
        roleGapErrors: {
          ...s.roleGapErrors,
          [roleId]: errorMessage(err, "Gap analysis is unavailable."),
        },
      }));
    }
  },

  reset: () => set({ ...initialState }),
}));
