import { create } from "zustand";
import {
  ApiError,
  getCareerPath,
  getRoleGapAnalysis,
  matchRoles,
  parseCv,
  submitManualCv,
  type CareerPathReport,
  type CVData,
  type EmbeddingProfile,
  type GapReport,
  type RoleMatch,
} from "@/lib/api";
import {
  applyEditsToCvData,
  cvDataToRecapEdits,
  cvDataToUserCareerProfile,
  fallbackIdentity,
  manualFormToInput,
  toConfirmedCvData,
  type RecapEdits,
} from "@/lib/cvData";
import {
  DEMO_CAREER_PATH_REPORTS,
  DEMO_CV_DATA,
  DEMO_EMBEDDING_PROFILE,
  DEMO_GAP_REPORTS,
  DEMO_IDENTITY,
  DEMO_ROLE_MATCHES,
  DEMO_SELECTED_ROLE_IDS,
} from "@/lib/demoData";
import { areSelectedPathsPrepared } from "@/lib/pathPreparation";
import type {
  AnalyzedSkill,
  CertificationItem,
  EducationItem,
  ExperienceItem,
  Identity,
  ManualProfileForm,
  ProjectItem,
} from "@/types";

export type Stage = "entry" | "recap" | "matching" | "directions" | "preparing_paths" | "focus";
export type DemoStage = "recap" | "roles" | "focus";

export const MAX_PICKS = 3;
const PATH_PREP_TIMEOUT_MS = 90000;
const DEMO_STAGE_TO_STAGE: Record<DemoStage, Stage> = {
  recap: "recap",
  roles: "directions",
  focus: "focus",
};

function errorMessage(err: unknown, fallback: string): string {
  if (err instanceof ApiError) return err.message;
  if (err instanceof Error) return err.message;
  return fallback;
}

type Store = {
  stage: Stage;
  setStage: (s: Stage) => void;

  /** Canonical parsed/assembled CV (source of truth sent to the backend). */
  cvData: CVData | null;

  /** Editable recap projections seeded from `cvData`. */
  skills: AnalyzedSkill[];
  addSkill: (name: string, confidence?: number) => void;
  removeSkill: (name: string) => void;

  interests: string[];
  addInterest: (name: string) => void;
  removeInterest: (name: string) => void;

  experiences: ExperienceItem[];
  addExperience: (e: ExperienceItem) => void;
  removeExperience: (idx: number) => void;

  educations: EducationItem[];
  addEducation: (e: EducationItem) => void;
  removeEducation: (idx: number) => void;

  certifications: CertificationItem[];
  addCertification: (c: CertificationItem) => void;
  removeCertification: (idx: number) => void;

  projects: ProjectItem[];
  addProject: (p: ProjectItem) => void;
  removeProject: (idx: number) => void;

  /** Career identity generated by the aggregate profile pipeline. */
  identity: Identity | null;
  setIdentityLead: (lead: string) => void;
  identityLoading: boolean;
  embeddingProfile: EmbeddingProfile | null;

  /** Role matching results. */
  roleMatches: RoleMatch[];
  matchAnalysis: string | null;
  selectedRoleIds: string[];
  toggleSelectedRole: (id: string) => void;
  selectedRoleId: string | null;
  setSelectedRoleId: (id: string | null) => void;
  roleGapReports: Record<string, GapReport>;
  roleGapLoading: Record<string, boolean>;
  roleGapErrors: Record<string, string | null>;
  careerPathReports: Record<string, CareerPathReport>;
  careerPathLoading: Record<string, boolean>;
  careerPathErrors: Record<string, string | null>;

  /** Async status for the current network action. */
  demoMode: boolean;
  loading: boolean;
  error: string | null;
  clearError: () => void;

  /** Async actions. */
  loadDemo: (target: DemoStage) => void;
  uploadCv: (file: File) => Promise<boolean>;
  submitManualProfile: (form: ManualProfileForm) => Promise<boolean>;
  generateIdentity: () => Promise<void>;
  runMatching: () => Promise<boolean>;
  loadRoleGapAnalysis: (roleId: string) => Promise<void>;
  loadCareerPath: (roleId: string) => Promise<void>;
  prepareSelectedPaths: (roleIds: string[]) => Promise<void>;
  reset: () => void;
};

function currentEdits(s: Store): RecapEdits {
  return {
    skills: s.skills,
    interests: s.interests,
    experiences: s.experiences,
    educations: s.educations,
    certifications: s.certifications,
    projects: s.projects,
  };
}

/** Build the CVData to send to the backend, merging recap edits into the base. */
function buildOutgoingCvData(s: Store): CVData | null {
  if (!s.cvData) return null;
  return applyEditsToCvData(s.cvData, currentEdits(s));
}

const initialState = {
  stage: "entry" as Stage,
  cvData: null as CVData | null,
  skills: [] as AnalyzedSkill[],
  interests: [] as string[],
  experiences: [] as ExperienceItem[],
  educations: [] as EducationItem[],
  certifications: [] as CertificationItem[],
  projects: [] as ProjectItem[],
  identity: null as Identity | null,
  identityLoading: false,
  embeddingProfile: null as EmbeddingProfile | null,
  roleMatches: [] as RoleMatch[],
  matchAnalysis: null as string | null,
  selectedRoleIds: [] as string[],
  selectedRoleId: null as string | null,
  roleGapReports: {} as Record<string, GapReport>,
  roleGapLoading: {} as Record<string, boolean>,
  roleGapErrors: {} as Record<string, string | null>,
  careerPathReports: {} as Record<string, CareerPathReport>,
  careerPathLoading: {} as Record<string, boolean>,
  careerPathErrors: {} as Record<string, string | null>,
  demoMode: false,
  loading: false,
  error: null as string | null,
};

let matchingRequest: Promise<boolean> | null = null;

export const useStageStore = create<Store>((set, get) => ({
  ...initialState,
  setStage: (s) => set({ stage: s }),

  addSkill: (name, confidence = 75) =>
    set((s) => {
      const v = name.trim();
      if (!v || s.skills.some((k) => k.name.toLowerCase() === v.toLowerCase())) return s;
      return { skills: [...s.skills, { name: v, confidence }] };
    }),
  removeSkill: (name) => set((s) => ({ skills: s.skills.filter((k) => k.name !== name) })),

  addInterest: (name) =>
    set((s) => {
      const v = name.trim();
      if (!v || s.interests.some((x) => x.toLowerCase() === v.toLowerCase())) return s;
      return { interests: [...s.interests, v] };
    }),
  removeInterest: (name) => set((s) => ({ interests: s.interests.filter((x) => x !== name) })),

  addExperience: (e) => set((s) => ({ experiences: [...s.experiences, e] })),
  removeExperience: (idx) =>
    set((s) => ({ experiences: s.experiences.filter((_, i) => i !== idx) })),

  addEducation: (e) => set((s) => ({ educations: [...s.educations, e] })),
  removeEducation: (idx) => set((s) => ({ educations: s.educations.filter((_, i) => i !== idx) })),

  addCertification: (c) => set((s) => ({ certifications: [...s.certifications, c] })),
  removeCertification: (idx) =>
    set((s) => ({ certifications: s.certifications.filter((_, i) => i !== idx) })),

  addProject: (p) => set((s) => ({ projects: [...s.projects, p] })),
  removeProject: (idx) => set((s) => ({ projects: s.projects.filter((_, i) => i !== idx) })),

  setIdentityLead: (lead) =>
    set((s) => {
      if (s.identity) return { identity: { ...s.identity, lead } };
      const fallback = s.cvData ? fallbackIdentity(s.cvData) : { archetype: "professional" };
      return { identity: { archetype: fallback.archetype, lead } };
    }),

  toggleSelectedRole: (id) =>
    set((s) => {
      if (s.selectedRoleIds.includes(id)) {
        return { selectedRoleIds: s.selectedRoleIds.filter((x) => x !== id) };
      }
      if (s.selectedRoleIds.length >= MAX_PICKS) return s;
      return { selectedRoleIds: [...s.selectedRoleIds, id] };
    }),

  setSelectedRoleId: (id) => set({ selectedRoleId: id }),
  clearError: () => set({ error: null }),

  loadDemo: (target) => {
    const selectedRoleIds = target === "focus" ? DEMO_SELECTED_ROLE_IDS : [];
    set({
      ...initialState,
      stage: DEMO_STAGE_TO_STAGE[target],
      cvData: DEMO_CV_DATA,
      embeddingProfile: DEMO_EMBEDDING_PROFILE,
      identity: DEMO_IDENTITY,
      ...cvDataToRecapEdits(DEMO_CV_DATA),
      roleMatches: DEMO_ROLE_MATCHES,
      matchAnalysis: "Demo fixture loaded without backend or OpenAI calls.",
      selectedRoleIds,
      selectedRoleId: selectedRoleIds[0] ?? null,
      roleGapReports: DEMO_GAP_REPORTS,
      careerPathReports: DEMO_CAREER_PATH_REPORTS,
      demoMode: true,
    });
  },

  /** Parse an uploaded PDF and seed the recap from the result. */
  uploadCv: async (file) => {
    set({ loading: true, error: null, demoMode: false });
    try {
      const result = await parseCv(file);
      const identitySummary = result.embedding_profile.career_identity_summary;
      set({
        cvData: result.cv_data,
        embeddingProfile: result.embedding_profile,
        identity: {
          archetype: identitySummary.label,
          lead: identitySummary.summary.trim() || fallbackIdentity(result.cv_data).lead,
        },
        ...cvDataToRecapEdits(result.cv_data),
        roleMatches: [],
        matchAnalysis: null,
        selectedRoleIds: [],
        selectedRoleId: null,
        roleGapReports: {},
        roleGapLoading: {},
        roleGapErrors: {},
        careerPathReports: {},
        careerPathLoading: {},
        careerPathErrors: {},
        demoMode: false,
        loading: false,
      });
      return true;
    } catch (err) {
      set({ loading: false, error: errorMessage(err, "Could not parse the CV.") });
      return false;
    }
  },

  /** Build a CVData from the manual form via the backend and seed the recap. */
  submitManualProfile: async (form) => {
    set({ loading: true, error: null, demoMode: false });
    try {
      const result = await submitManualCv(manualFormToInput(form));
      const identitySummary = result.embedding_profile.career_identity_summary;
      set({
        cvData: result.cv_data,
        embeddingProfile: result.embedding_profile,
        identity: {
          archetype: identitySummary.label,
          lead: identitySummary.summary.trim() || fallbackIdentity(result.cv_data).lead,
        },
        ...cvDataToRecapEdits(result.cv_data),
        roleMatches: [],
        matchAnalysis: null,
        selectedRoleIds: [],
        selectedRoleId: null,
        roleGapReports: {},
        roleGapLoading: {},
        roleGapErrors: {},
        careerPathReports: {},
        careerPathLoading: {},
        careerPathErrors: {},
        demoMode: false,
        loading: false,
      });
      return true;
    } catch (err) {
      set({ loading: false, error: errorMessage(err, "Could not build the profile.") });
      return false;
    }
  },

  /** Legacy local fallback; entry pipeline now provides identity before Recap. */
  generateIdentity: async () => {
    const outgoing = buildOutgoingCvData(get());
    if (!outgoing) return;
    set({ identityLoading: true });
    try {
      set({
        identity: fallbackIdentity(outgoing),
        identityLoading: false,
      });
    } catch {
      // Identity is non-blocking — fall back to a CV-derived statement.
      set({
        identity: fallbackIdentity(outgoing),
        identityLoading: false,
      });
    }
  },

  /** Match the (edited) CV against ESCO roles using the embedding pipeline query text. */
  runMatching: async () => {
    if (matchingRequest) return matchingRequest;

    const request = (async () => {
      const state = get();
      const outgoing = buildOutgoingCvData(state);
      if (!outgoing) {
        set({ error: "No CV data to match." });
        return false;
      }
      if (state.demoMode && state.roleMatches.length > 0) {
        set({ cvData: outgoing, error: null, loading: false });
        return true;
      }
      set({ loading: true, error: null, cvData: outgoing });
      try {
        const result = await matchRoles(cvDataToUserCareerProfile(outgoing, state.identity), 9);
        set({
          roleMatches: result.matched_roles,
          matchAnalysis: result.analysis,
          selectedRoleIds: [],
          roleGapReports: {},
          roleGapLoading: {},
          roleGapErrors: {},
          careerPathReports: {},
          careerPathLoading: {},
          careerPathErrors: {},
          loading: false,
        });
        return true;
      } catch (err) {
        set({ loading: false, error: errorMessage(err, "Role matching is unavailable.") });
        return false;
      }
    })();

    matchingRequest = request.finally(() => {
      matchingRequest = null;
    });
    return matchingRequest;
  },

  loadRoleGapAnalysis: async (roleId) => {
    const state = get();
    if (state.roleGapReports[roleId] || state.roleGapLoading[roleId]) return;
    const outgoing = buildOutgoingCvData(state);
    if (!outgoing) {
      set((s) => ({ roleGapErrors: { ...s.roleGapErrors, [roleId]: "No CV data to analyze." } }));
      return;
    }

    set((s) => ({
      roleGapLoading: { ...s.roleGapLoading, [roleId]: true },
      roleGapErrors: { ...s.roleGapErrors, [roleId]: null },
    }));
    try {
      const report = await getRoleGapAnalysis(roleId, toConfirmedCvData(outgoing, state.identity));
      set((s) => ({
        roleGapReports: { ...s.roleGapReports, [roleId]: report },
        roleGapLoading: { ...s.roleGapLoading, [roleId]: false },
      }));
    } catch (err) {
      set((s) => ({
        roleGapLoading: { ...s.roleGapLoading, [roleId]: false },
        roleGapErrors: {
          ...s.roleGapErrors,
          [roleId]: errorMessage(err, "Gap analysis is unavailable."),
        },
      }));
    }
  },

  loadCareerPath: async (roleId) => {
    const state = get();
    if (state.careerPathReports[roleId] || state.careerPathLoading[roleId]) return;
    const outgoing = buildOutgoingCvData(state);
    if (!outgoing) {
      set((s) => ({
        careerPathErrors: { ...s.careerPathErrors, [roleId]: "No CV data to map." },
      }));
      return;
    }

    set((s) => ({
      careerPathLoading: { ...s.careerPathLoading, [roleId]: true },
      careerPathErrors: { ...s.careerPathErrors, [roleId]: null },
    }));
    try {
      const report = await getCareerPath(roleId, toConfirmedCvData(outgoing, state.identity));
      set((s) => ({
        careerPathReports: { ...s.careerPathReports, [roleId]: report },
        careerPathLoading: { ...s.careerPathLoading, [roleId]: false },
      }));
    } catch (err) {
      set((s) => ({
        careerPathLoading: { ...s.careerPathLoading, [roleId]: false },
        careerPathErrors: {
          ...s.careerPathErrors,
          [roleId]: errorMessage(err, "Career roadmap is unavailable."),
        },
      }));
    }
  },

  prepareSelectedPaths: async (roleIds) => {
    const selected = [...new Set(roleIds.filter(Boolean))];
    if (selected.length === 0) return;

    await Promise.allSettled(
      selected.flatMap((roleId) => [
        get().loadCareerPath(roleId),
        get().loadRoleGapAnalysis(roleId),
      ]),
    );

    const startedAt = Date.now();
    while (!areSelectedPathsPrepared(selected, get())) {
      if (Date.now() - startedAt > PATH_PREP_TIMEOUT_MS) {
        set((s) => {
          const careerPathErrors = { ...s.careerPathErrors };
          const roleGapErrors = { ...s.roleGapErrors };
          const careerPathLoading = { ...s.careerPathLoading };
          const roleGapLoading = { ...s.roleGapLoading };

          for (const roleId of selected) {
            if (!s.careerPathReports[roleId] && !careerPathErrors[roleId]) {
              careerPathErrors[roleId] = "Career roadmap is still unavailable.";
              careerPathLoading[roleId] = false;
            }
            if (!s.roleGapReports[roleId] && !roleGapErrors[roleId]) {
              roleGapErrors[roleId] = "Gap analysis is still unavailable.";
              roleGapLoading[roleId] = false;
            }
          }

          return { careerPathErrors, roleGapErrors, careerPathLoading, roleGapLoading };
        });
        return;
      }
      await sleep(150);
    }
  },

  reset: () => set({ ...initialState }),
}));

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => window.setTimeout(resolve, ms));
}
