export const ROLE_PRESETS = [
  "Senior Backend Developer",
  "Backend Developer",
  "Full-Stack Engineer",
  "Frontend Engineer",
  "DevOps Engineer",
  "Tech Lead",
  "Engineering Manager",
  "Data Engineer",
  "Cloud Engineer",
  "Product Designer",
];

export const DEGREE_LEVELS = [
  "B.Sc.",
  "M.Sc.",
  "B.A.",
  "M.A.",
  "B.Eng.",
  "M.Eng.",
  "PhD",
  "MBA",
  "Abitur",
  "Bootcamp",
  "Other",
];

export const LANGUAGE_LEVELS = ["A1", "A2", "B1", "B2", "C1", "C2", "Native"];

export const FIELD_OF_STUDY_PRESETS = [
  "Computer Science",
  "Software Engineering",
  "Information Systems",
  "Information Technology",
  "Data Science",
  "Artificial Intelligence",
  "Machine Learning",
  "Cybersecurity",
  "Electrical Engineering",
  "Electronics Engineering",
  "Mechanical Engineering",
  "Mechatronics",
  "Robotics",
  "Civil Engineering",
  "Chemical Engineering",
  "Industrial Engineering",
  "Aerospace Engineering",
  "Biomedical Engineering",
  "Mathematics",
  "Applied Mathematics",
  "Statistics",
  "Physics",
  "Chemistry",
  "Biology",
  "Biotechnology",
  "Business Administration",
  "Management",
  "Finance",
  "Accounting",
  "Economics",
  "Marketing",
  "Human Resources",
  "Supply Chain Management",
  "Entrepreneurship",
  "Psychology",
  "Sociology",
  "Political Science",
  "Law",
  "Communications",
  "Media Studies",
  "Journalism",
  "Graphic Design",
  "Product Design",
  "Industrial Design",
  "Architecture",
  "Urban Planning",
  "Education",
  "Linguistics",
  "Philosophy",
  "History",
  "Medicine",
  "Nursing",
  "Public Health",
  "Pharmacy",
  "Environmental Science",
  "Geography",
  "Digital Media",
  "Game Development",
  "Human-Computer Interaction",
  "Other",
];

export const SKILL_PRESETS = [
  // Languages
  "Python",
  "JavaScript",
  "TypeScript",
  "Java",
  "C",
  "C++",
  "C#",
  "Go",
  "Rust",
  "Kotlin",
  "Swift",
  "Ruby",
  "PHP",
  "Scala",
  "R",
  "MATLAB",
  "SQL",
  "Bash",
  // Frontend
  "React",
  "Next.js",
  "Vue.js",
  "Angular",
  "Svelte",
  "HTML",
  "CSS",
  "Tailwind CSS",
  "Redux",
  "React Native",
  // Backend / frameworks
  "Node.js",
  "Express",
  "Django",
  "Flask",
  "FastAPI",
  "Spring Boot",
  ".NET",
  "Ruby on Rails",
  "GraphQL",
  "RESTful APIs",
  "gRPC",
  "Microservices Architecture",
  // Data / ML
  "Pandas",
  "NumPy",
  "scikit-learn",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "Apache Spark",
  "Hadoop",
  "Airflow",
  "dbt",
  "Machine Learning",
  "Deep Learning",
  "Natural Language Processing",
  "Computer Vision",
  "Data Analysis",
  "Data Visualization",
  "Tableau",
  "Power BI",
  // Databases
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "Elasticsearch",
  "SQLite",
  "Cassandra",
  "DynamoDB",
  // Cloud / DevOps
  "AWS",
  "AWS EC2",
  "AWS Lambda",
  "Azure",
  "Google Cloud Platform",
  "Docker",
  "Kubernetes",
  "Terraform",
  "Ansible",
  "Jenkins",
  "GitHub Actions",
  "CI/CD",
  "Linux",
  "Nginx",
  "Kafka",
  "RabbitMQ",
  // Tooling / practices
  "Git",
  "System Design",
  "Agile",
  "Scrum",
  "Test-Driven Development",
  "Unit Testing",
  "Cypress",
  "Playwright",
  "Jira",
  "Figma",
  "UI/UX Design",
  "Object-Oriented Programming",
  "Functional Programming",
  "Data Structures",
  "Algorithms",
  "Mentoring",
  "Technical Leadership",
];
